### PR TITLE
do not activate devices on enum

### PR DESCRIPTION
**Pull request by summeroff**

### CODE REVIEW

**Comment by EddyGharbi** [comment]
From the title of this PR, I understand that the code is supposed to **not** activate devices when enumerating them, although when looking at the code it is actually doing the opposite? Am I understanding correctly?

**Comment by summeroff** [comment]
Changes in code make what it only activates devices if source is active. 
It is needed because when frontend enumerate devices at start it create not active source and get device from it.

**Comment by EddyGharbi** [comment]
Sounds good makes sense

**Comment by EddyGharbi** [comment]
I just merged the submodule branch, could you update your PR to use the latest base branch of the module?

**Comment by summeroff** [comment]
rebased this branch to streamlabs-24.0.3

**Review by EddyGharbi — APPROVED** [review]

**Comment by EddyGharbi** [comment]
Approved, waiting on the tests to pass and I'll merge.

**Pull request merged**
