### PR TITLE
let check if output is busy before updating settings

### PR DESCRIPTION
**Pull request by summeroff**

### CODE REVIEW

**Comment by EddyGharbi** [comment]
Looks good but I would replace all the `is_ready_for_settings_update` by `is_busy`, what do you think?

**Comment by summeroff** [comment]
Was thinking the same. Something short like is_busy is look better. 

But I had doubts that it may mislead future developers. It can be confusing on what restrictions is_busy implies other than not updating settings.

**Comment by EddyGharbi** [comment]
I see, `is_ready_to_update` might be better then?

**Comment by EddyGharbi** [comment]
`is_ready_for_update` looks more correct actually.

**Comment by summeroff** [comment]
yes. this name looks better. will update.

**Comment by summeroff** [comment]
functions names are updated

**Review by EddyGharbi — APPROVED** [review]

**Pull request merged**
